### ISSUE TITLE
Error in Load CAME results

### ISSUE THREAD

**Issue by LalicJ** [XingyanLiu/CAME#26]
Hi, I'm sorry to bother you again. TWhen I try to reload the CAME resulting data 
`dpair, model = came.load_dpair_and_model(came_resdir)`, I got a KeyError as follows:
`[*] Setting dataset names:
        0-->PR_Ms
        1-->PR_NHP
[*] Setting aligned features for observation nodes (self._features)
Traceback (most recent call last):
  File "softs/conda/Conda_data/envs/env_came/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "softs/conda/Conda_data/envs/env_came/lib/python3.8/site-packages/came/utils/analyze.py", line 115, in load_dpair_and_model
    dpair = DataPair(**element_dict)
  File "softs/conda/Conda_data/envs/env_came/lib/python3.8/site-packages/came/datapair/unaligned.py", line 120, in __init__
    self.set_features(features, varnames_feat)
  File "softs/conda/Conda_data/envs/env_came/lib/python3.8/site-packages/came/datapair/unaligned.py", line 597, in set_features
    self.dataset_names[0]: varnames_feat[0],
  File "softs/conda/Conda_data/envs/env_came/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "softs/conda/Conda_data/envs/env_came/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 0
`

Here is my env_came environment:
Package             Version
------------------- ---------
anndata             0.8.0
came                0.1.9
certifi             2022.12.7
charset-normalizer  3.0.1
contourpy           1.0.7
cycler              0.11.0
dgl                 0.9.0
fonttools           4.38.0
h5py                3.8.0
idna                3.4
igraph              0.10.4
importlib-metadata  6.0.0
importlib-resources 5.12.0
joblib              1.2.0
kiwisolver          1.4.4
leidenalg           0.9.1
llvmlite            0.39.1
matplotlib          3.7.0
natsort             8.2.0
networkx            3.0
numba               0.56.4
numpy               1.23.2
packaging           23.0
pandas              1.5.3
patsy               0.5.3
Pillow              9.4.0
pip                 22.3.1
psutil              5.9.4
pynndescent         0.5.8
pyparsing           3.0.9
python-dateutil     2.8.2
python-igraph       0.10.4
pytz                2022.7.1
requests            2.28.2
scanpy              1.9.2
scikit-learn        1.1.2
scipy               1.10.1
seaborn             0.12.2
session-info        1.0.0
setuptools          65.6.3
six                 1.16.0
statsmodels         0.13.5
stdlib-list         0.8.0
texttable           1.6.7
threadpoolctl       3.1.0
torch               1.12.1
tqdm                4.64.1
typing_extensions   4.5.0
umap-learn          0.5.3
urllib3             1.26.14
wheel               0.38.4
zipp                3.14.0

Hope to your reply. Thanks for your time.

**Comment by Soap4** [comment]
@LalicJ
**Hi LalicJ, I recently encountered the same error as you did, and I could not manage to solve this until I check the source code of:**
`came.load_dpair_and_model`

**Briefly, I check the source code with**
```
import inspect
inspect.getsource(came.load_dpair_and_model)
```
**and got the following output:**
```
def load_dpair_and_model(
        dirname: Union[str, Path],
        subdir_model: str = '_models',
        ckpt: Union[int, str, None] = None,
):
    import torch
    dirname = Path(dirname)
    model_dir = dirname / subdir_model
    element_dict = load_pickle(dirname / 'datapair_init.pickle')
    model_params = load_json_dict(dirname / 'model_params.json')

    if 'vv_adj' not in element_dict.keys():
        dpair = AlignedDataPair(**element_dict)
        model = CGCNet(**model_params)
    else:
        dpair = DataPair(**element_dict)
        model = CGGCNet(**model_params)
    if os.path.exists(dirname / 'obs.csv'):
        dpair.set_common_obs_annos(
                pd.read_csv(dirname / 'obs.csv', index_col=0),
                ignore_index=True
                )
    if ckpt is None:
        ckpt = _infer_ckpt(model_dir)
    if not torch.cuda.is_available():
        map_location = torch.device('cpu')
    else:
        map_location = None
    model.load_state_dict(
        torch.load(model_dir / f'weights_epoch{ckpt}.pt',
                   map_location=map_location)
    )
    return dpair, model
```
**it seems that the error was caused by line13, and i could not solve it**
`dpair = AlignedDataPair(**element_dict)`

**So i manage to load the `model` by following independent code as the function did:**
```
import torch
dirname = Path("_output/dir-name-of-output")
model_dir = dirname / "_models"
model_params = came.load_json_dict(dirname / 'model_params.json')
model = came.CGGCNet(**model_params)
ckpt = came.load_json_dict("checkpoint_dict.json")['recommended']
map_location = torch.device('cpu')
model.load_state_dict(torch.load(model_dir / f'weights_epoch{ckpt}.pt',map_location=map_location))
```
As for other pre-computed results, including:
```
dpair = outputs['dpair']
trainer = outputs['trainer']
h_dict = outputs['h_dict']
out_cell = outputs['out_cell']
predictor = outputs['predictor']
```

I found out that the `hickle `module turns out to be a very useful module for me to store those results😂
So I save those results by the following code, respectively.
```
import hickle as hkl
hkl.dump(outputs['dpair'], resdir / "dpair.hkl")
hkl.dump(outputs['h_dict'], resdir / "h_dict.hkl")
hkl.dump(outputs['out_cell'], resdir / "out_cell.hkl")
hkl.dump(outputs['predictor'], resdir / "predictor.hkl")

## and load it with
hkl.load()
```

Hope this help😊

**Comment by LalicJ** [comment]
@Soap4 Thank you! I'll try it.

**Comment by XingyanLiu** [comment]
bug-fixed in version 0.1.10
